services:
  - type: web
    name: name-kanji-converter
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    region: oregon
